### ISSUE TITLE
OrdersTotal() is in trouble

### ISSUE THREAD

**Issue by DataScientist001** [apiaryfund/Alveo#1]
While using OrdersTotal() in my Algos, sometimes i get errors.... seems to be random, as sometimes i reset the Alveo Platform and they sometimes stop, sometimes not.

Since this function doesn't take any parameters, i am assuming the erros must be comming from sources other than my codes.

**Comment by DataScientist001** [comment]
Still in trouble, here is the error message i am getting: 

Object reference not set to an instance of an object.
at Alveo.UserCode.CodeBase.OrdersTotal()
   at Alveo.UserCode.TradeSyncReceiver.PortfolioBalance(String pSymbol, Double pVolume, Double pAlveoCMD)
   at Alveo.UserCode.TradeSyncReceiver.SendConfirmOpen(String SCOsymbol, Int32 SCOcmd, Double SCOvolume, Double SCOprice, Int32 SCOslippage, Double SCOstoploss, Double SCOtakeprofit, String SCOcomment, Int32 SCOmagic, datetime SCOexpiration, color SCOarrow_color)
